name: Playwright Tests
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  checks: write
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm ci
        npm install -D @playwright/test allure-playwright

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
      continue-on-error: true

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results
        path: test-results/

    - name: Add Playwright report to pull request
      uses: daun/playwright-report-summary@v3
      if: always()
      with:
        report-file: test-results/results.json
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Allure CLI
      run: |
        npm install -g allure-commandline
        npm install -g allure-playwright

    - name: Create Allure Results Directory
      run: mkdir -p allure-results
      if: always()

    - name: Setup Pages
      uses: actions/configure-pages@v4
      if: always()

    - name: Create gh-pages branch
      run: |
        git checkout --orphan gh-pages || true
        git reset --hard || true
        git commit --allow-empty -m "Initial gh-pages commit" || true
        git checkout main
      continue-on-error: true

    - name: Generate Allure Report
      run: allure generate --clean
      if: always()

    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report with history
      uses: simple-elf/allure-report-action@v1.9
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: allure-results

    - name: Deploy report to Github Pages
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
        force_orphan: true
        commit_message: "docs: update allure report"