name: Playwright Tests
on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '21 20 * * *'  # Runs daily at midnight UTC 4 pm pct
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write
  checks: write
  pull-requests: write
  actions: write
  statuses: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm ci --no-optional
        npm install -D @playwright/test allure-playwright
        npm install -g allure-commandline

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Create directories
      run: |
        mkdir -p test-results
        mkdir -p playwright-report
        mkdir -p allure-results
        mkdir -p allure-report

    - name: Run Playwright tests
      run: |
        npx playwright test --reporter=list,html,json,allure-playwright
      continue-on-error: true
      env:
        PLAYWRIGHT_JSON_OUTPUT_NAME: test-results/results.json
        ALLURE_RESULTS_DIR: allure-results

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v4
      with:
        static_site_generator: "null"
        enablement: true

    - name: Add Playwright report to pull request
      if: always()
      uses: daun/playwright-report-summary@v3
      with:
        report-file: test-results/results.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        create-comment: true

    - name: Generate Allure Report
      if: always()
      run: |
        allure generate allure-results -o allure-report --clean

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          playwright-report/
          allure-report/
        retention-days: 30

    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'docs: update test report [skip ci]'

    - name: Send Scheduled Run Summary to Slack
      if: github.event_name == 'schedule'
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,took
        text: |
          Daily Test Run Summary:
          Status: ${{ job.status }}
          Total Tests: ${{ steps.test-results.outputs.total }}
          Passed: ${{ steps.test-results.outputs.passed }}
          Failed: ${{ steps.test-results.outputs.failed }}
          View Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}